### PR TITLE
Fix ie svg

### PR DESCRIPTION
**Pull request by robert-stclair**
### :zap: Front End Dev Checklist :zap:

* [ ] Can you use existing components? Or add modifiers to existing components? 
* [ ] Does your code follow BEM?
* [ ] Does the component work on screen widths from 340px -> 2000px?  
* [ ] Is your HTML valid? 
* [ ] Does your code meet WCAG guidelines? 
* [ ] Did you update the style guide?

### CODE REVIEW

**Comment by zhuoyanlee** [comment]
rather than introducing new CSS class, can we just replace the svg in the existing css class?

**Comment by robert-stclair** [comment]
Yes - this is just a test first. I'm not sure this will work. I would rather be testing locally or on a PR but I can't. So I have made a few classes to try different approaches. Will clean up after.

**Comment by robert-stclair** [comment]
I am using SVG code from font awesome assuming theirs might be more widely compatible.

**Comment by zhuoyanlee** [comment]
let me see if i can get the PR branch fixed

**Review by zhuoyanlee — APPROVED** [review]

**Pull request merged**
