### PR TITLE
giant sitemap

### PR DESCRIPTION
**Pull request by AllySummers**
### :zap: Front End Dev Checklist :zap:

@zhuoyanlee here is a PR for the sitemap for all files for you :)

### CODE REVIEW

**Comment by zhuoyanlee** [comment]
Is the sitemap supposed to be https://myservice-disco-pr-999.herokuapp.com/sitemap? I'm getting an error

**Comment by AllySummers** [comment]
oh was writing to you in Slack

for some reason not working on heroku :(
@sitrobotsit  said it had to be dynamic **and** include the HTML title of every page and to do that i would either have to make a GET request to every single page and ask for the title OR read every single file and do a regex match for `<title>(.*)</title>`
if it can just include the the location of the file and the link to it, it should work on heroku

i.e.:
[/auth/claim/claim1a](https://myservice-disco.herokuapp.com/auth/claim/claim1a)

**Comment by AllySummers** [comment]
here's what it looks like on my local: 
image

**Comment by sitrobotsit** [comment]
a few things; 

1) It doesn't need to be dynamic in the sense that happens at request time. I imagined this happening as part of the gulp build. But given this page isn't going to be hit very much, this preforment issue isn't a big deal seeing how this page won't be hit that often. 
2) You required two new npm packages without updating the package.json. It worked this time because 'util' and 'path' are so ubiquitous. But in future, please add them in package.json. 
3) If you're going to change the way npm packages are called in index.js, please make it consistent e.g. change `let express = require('express'),` to `const { express } = require('express'),`
4) Below is the heroku error log. Looks like your path is a bit wrong. Perhaps your Windows environment is more forgiving. 


{ Error: ENOENT: no such file or directory, open './views//app/views/auth/change-email-enter-code.ejs'
2019-05-30T23:09:25.134331+00:00 app[web.1]:     at Object.fs.openSync (fs.js:646:18)
2019-05-30T23:09:25.134334+00:00 app[web.1]:     at Object.fs.readFileSync (fs.js:551:33)
2019-05-30T23:09:25.134335+00:00 app[web.1]:     at files.forEach (/app/index.js:121:24)
2019-05-30T23:09:25.134337+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2019-05-30T23:09:25.134340+00:00 app[web.1]:     at getFiles.then.files (/app/index.js:118:14)
2019-05-30T23:09:25.134343+00:00 app[web.1]:     at <anonymous>
2019-05-30T23:09:25.134346+00:00 app[web.1]:   errno: -2,
2019-05-30T23:09:25.134347+00:00 app[web.1]:   code: 'ENOENT',
2019-05-30T23:09:25.134349+00:00 app[web.1]:   syscall: 'open',
2019-05-30T23:09:25.134351+00:00 app[web.1]:   path: './views//app/views/auth/change-email-enter-code.ejs' }

**Pull request merged**
